server:
  port: 8080
  title: CHAT-APP
  version: 1.0.0
  shutdown: graceful

spring:
  main:
    web-application-type: reactive
  lifecycle:
    timeout-per-shutdown-phase: 20s
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chat_app
    username: root
    password: dlab9185

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha


api:
  base-url:
    urls:
#      dims-dev: http://192.168.0.28:48080
      dims-dev: http://fbc.digitalab.co.kr:18080/dims-dev-service
      dims-prod: http://fbc.digitalab.co.kr:18080/dims-service

